[tool.poetry]
name = "flask-app"
version = "0.1.0"
description = ""
authors = ["Vinay"]

[tool.poetry.dependencies]
python = "^3.11"
flask = "^2.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
